follow_ball:
  ros__parameters:
    use_sim_time: false
    max_vel: 0.25
    min_l_vel: 0.0
    min_l_vel: -0.25
    turn_right_vel: -0.25
    turn_left_vel: 0.25

hsv_filter_node:
  ros__parameters:
    use_sim_time: false
    min_h: 160
    max_h: 180
    min_s: 120
    max_s: 255
    min_v: 130
    max_v: 255

obstacle_detector_node:
  ros__parameters:
    use_sim_time: false
    min_distance: 1.0
